/**
 * Shared VFSTR.AI Admin PDF report renderer (jsPDF — already a client dependency).
 * Cream + teal palette for external sharing.
 */
import { jsPDF } from 'jspdf';
import { ADMIN_COLORS } from './adminAuth';

const MARGIN = 48;
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const CONTENT_W = PAGE_W - MARGIN * 2;

const COLORS = {
  teal: ADMIN_COLORS.tealAccent,
  tealDark: ADMIN_COLORS.tealAccentHover,
  cream: ADMIN_COLORS.cream,
  creamAlt: ADMIN_COLORS.creamAlt,
  border: ADMIN_COLORS.creamBorder,
  ink: ADMIN_COLORS.ink,
  muted: ADMIN_COLORS.inkMuted,
  white: '#FFFFFF',
  warn: ADMIN_COLORS.warn,
  ready: '#0D9488',
  intermediate: '#D97706',
  beginner: '#DC2626',
};

const hexToRgb = (hex) => {
  const h = String(hex).replace('#', '');
  const n = parseInt(h.length === 3 ? h.split('').map((c) => c + c).join('') : h, 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
};

const setFill = (doc, hex) => {
  const { r, g, b } = hexToRgb(hex);
  doc.setFillColor(r, g, b);
};

const setDraw = (doc, hex) => {
  const { r, g, b } = hexToRgb(hex);
  doc.setDrawColor(r, g, b);
};

const setText = (doc, hex) => {
  const { r, g, b } = hexToRgb(hex);
  doc.setTextColor(r, g, b);
};

const fmtNum = (n, suffix = '') => {
  if (n == null || !Number.isFinite(Number(n))) return '—';
  return `${Number(n)}${suffix}`;
};

const fmtDate = (iso) => {
  if (!iso) return '—';
  return new Date(iso).toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

const shortDate = (iso) => {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
};

/** Create a stateful page drawer. */
export const createReportDoc = (title = 'VFSTR.AI Report') => {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  let y = MARGIN;

  const ensureSpace = (need = 40) => {
    if (y + need > PAGE_H - 56) {
      drawFooter(doc);
      doc.addPage();
      paintPageBackground(doc);
      y = MARGIN;
    }
  };

  const state = {
    doc,
    get y() {
      return y;
    },
    set y(v) {
      y = v;
    },
    ensureSpace,
    title,
  };

  paintPageBackground(doc);
  return state;
};

const paintPageBackground = (doc) => {
  setFill(doc, COLORS.cream);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
};

const drawFooter = (doc) => {
  setFill(doc, COLORS.creamAlt);
  doc.rect(0, PAGE_H - 36, PAGE_W, 36, 'F');
  setText(doc, COLORS.muted);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Generated by VFSTR.AI Admin Panel', PAGE_W / 2, PAGE_H - 16, { align: 'center' });
};

/** Teal header band + title block */
export const drawReportHeader = (state, {
  title,
  subtitle,
  generatedAt,
  dateRangeLabel,
}) => {
  const { doc } = state;
  setFill(doc, COLORS.teal);
  doc.rect(0, 0, PAGE_W, 78, 'F');
  setText(doc, COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(String(title || 'Report'), MARGIN, 36);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(String(subtitle || ''), MARGIN, 56);

  state.y = 100;
  setText(doc, COLORS.muted);
  doc.setFontSize(10);
  doc.text(`Generated: ${fmtDate(generatedAt)}`, MARGIN, state.y);
  state.y += 14;
  doc.text(`Date range covered: ${dateRangeLabel || '—'}`, MARGIN, state.y);
  state.y += 22;
};

export const drawSectionTitle = (state, text) => {
  state.ensureSpace(36);
  const { doc } = state;
  setText(doc, COLORS.tealDark);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(String(text), MARGIN, state.y);
  state.y += 6;
  setDraw(doc, COLORS.border);
  doc.setLineWidth(1);
  doc.line(MARGIN, state.y, MARGIN + CONTENT_W, state.y);
  state.y += 16;
};

export const drawParagraph = (state, text, opts = {}) => {
  const { doc } = state;
  doc.setFont('helvetica', opts.bold ? 'bold' : 'normal');
  doc.setFontSize(opts.size || 10);
  setText(doc, opts.color || COLORS.ink);
  const lines = doc.splitTextToSize(String(text || ''), CONTENT_W);
  state.ensureSpace(lines.length * 13 + 8);
  doc.text(lines, MARGIN, state.y);
  state.y += lines.length * 13 + (opts.gap ?? 10);
};

/** Summary stat cards in a row */
export const drawStatBlock = (state, stats) => {
  state.ensureSpace(78);
  const { doc } = state;
  const cols = Math.min(stats.length, 4);
  const gap = 10;
  const cardW = (CONTENT_W - gap * (cols - 1)) / cols;
  const cardH = 58;
  const startY = state.y;

  stats.slice(0, 4).forEach((stat, i) => {
    const x = MARGIN + i * (cardW + gap);
    setFill(doc, COLORS.white);
    setDraw(doc, COLORS.border);
    doc.roundedRect(x, startY, cardW, cardH, 6, 6, 'FD');
    setText(doc, COLORS.muted);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(String(stat.label), x + 10, startY + 16);
    setText(doc, COLORS.tealDark);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(String(stat.value), x + 10, startY + 40);
  });

  state.y = startY + cardH + 18;

  if (stats.length > 4) {
    state.ensureSpace(78);
    const startY2 = state.y;
    stats.slice(4).forEach((stat, i) => {
      const x = MARGIN + i * (cardW + gap);
      setFill(doc, COLORS.white);
      setDraw(doc, COLORS.border);
      doc.roundedRect(x, startY2, cardW, cardH, 6, 6, 'FD');
      setText(doc, COLORS.muted);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.text(String(stat.label), x + 10, startY2 + 16);
      setText(doc, COLORS.tealDark);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.text(String(stat.value), x + 10, startY2 + 40);
    });
    state.y = startY2 + cardH + 18;
  }
};

/** Horizontal bar chart for readiness bands */
export const drawBandChart = (state, bands) => {
  if (!bands) return;
  drawSectionTitle(state, 'Score distribution (readiness bands)');
  const { doc } = state;
  const total = (bands.Beginner || 0) + (bands.Intermediate || 0) + (bands.Ready || 0);
  const rows = [
    { label: 'Ready', count: bands.Ready || 0, color: COLORS.ready },
    { label: 'Intermediate', count: bands.Intermediate || 0, color: COLORS.intermediate },
    { label: 'Beginner', count: bands.Beginner || 0, color: COLORS.beginner },
  ];

  if (!total) {
    drawParagraph(state, 'No students available to chart readiness bands.', { color: COLORS.muted });
    return;
  }

  const barMax = CONTENT_W - 130;
  rows.forEach((row) => {
    state.ensureSpace(28);
    const { doc: d } = state;
    setText(d, COLORS.ink);
    d.setFont('helvetica', 'normal');
    d.setFontSize(10);
    d.text(row.label, MARGIN, state.y + 10);
    const w = Math.max(4, (row.count / total) * barMax);
    setFill(d, row.color);
    d.roundedRect(MARGIN + 90, state.y, w, 14, 3, 3, 'F');
    setText(d, COLORS.muted);
    d.text(`${row.count} (${Math.round((row.count / total) * 100)}%)`, MARGIN + 100 + w, state.y + 11);
    state.y += 24;
  });
  state.y += 8;
};

/** Sub-score table / mini bars */
export const drawSubScoreSection = (state, subScores) => {
  drawSectionTitle(state, 'Average sub-scores');
  if (!subScores) {
    drawParagraph(state, 'No completed interview score breakdowns available yet.', { color: COLORS.muted });
    return;
  }

  const rows = [
    { label: 'Technical knowledge', value: subScores.technical },
    { label: 'Problem solving', value: subScores.problemSolving },
    { label: 'Communication', value: subScores.communication },
    { label: 'Confidence', value: subScores.confidence },
    { label: 'Answer relevance', value: subScores.answerRelevance },
  ];

  const { doc } = state;
  const barMax = CONTENT_W - 160;
  rows.forEach((row) => {
    state.ensureSpace(26);
    setText(doc, COLORS.ink);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(row.label, MARGIN, state.y + 10);
    const v = Number(row.value) || 0;
    setFill(doc, COLORS.creamAlt);
    doc.roundedRect(MARGIN + 130, state.y, barMax, 12, 3, 3, 'F');
    setFill(doc, COLORS.teal);
    doc.roundedRect(MARGIN + 130, state.y, Math.max(2, (v / 100) * barMax), 12, 3, 3, 'F');
    setText(doc, COLORS.tealDark);
    doc.setFont('helvetica', 'bold');
    doc.text(fmtNum(row.value), MARGIN + 130 + barMax + 8, state.y + 10);
    state.y += 22;
  });
  state.y += 8;
};

export const drawPerformersTable = (state, title, rows) => {
  drawSectionTitle(state, title);
  if (!rows?.length) {
    drawParagraph(state, 'No scored students in this set yet.', { color: COLORS.muted });
    return;
  }

  const { doc } = state;
  const cols = [
    { key: 'name', label: 'Student', w: 160 },
    { key: 'averageScore', label: 'Avg score', w: 70 },
    { key: 'readinessLevel', label: 'Band', w: 90 },
    { key: 'totalInterviews', label: 'Interviews', w: 70 },
  ];

  state.ensureSpace(24);
  setFill(doc, COLORS.teal);
  doc.rect(MARGIN, state.y - 10, CONTENT_W, 20, 'F');
  setText(doc, COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  let x = MARGIN + 8;
  cols.forEach((c) => {
    doc.text(c.label, x, state.y + 3);
    x += c.w;
  });
  state.y += 16;

  rows.forEach((row, idx) => {
    state.ensureSpace(20);
    if (idx % 2 === 0) {
      setFill(doc, COLORS.white);
      doc.rect(MARGIN, state.y - 10, CONTENT_W, 18, 'F');
    }
    setText(doc, COLORS.ink);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    let cx = MARGIN + 8;
    doc.text(String(row.name || '—').slice(0, 32), cx, state.y + 2);
    cx += cols[0].w;
    doc.text(fmtNum(row.averageScore), cx, state.y + 2);
    cx += cols[1].w;
    doc.text(String(row.readinessLevel || '—'), cx, state.y + 2);
    cx += cols[2].w;
    doc.text(fmtNum(row.totalInterviews), cx, state.y + 2);
    state.y += 18;
  });
  state.y += 10;
};

export const drawWeaknesses = (state, weaknesses) => {
  if (!weaknesses?.length) return;
  drawSectionTitle(state, 'Most common improvement themes');
  drawParagraph(
    state,
    'Derived from repeated AI feedback improvement lines (platform does not expose tagged weakness categories).',
    { size: 9, color: COLORS.muted, gap: 8 },
  );
  weaknesses.forEach((w, i) => {
    drawParagraph(state, `${i + 1}. ${w.label}  ·  ${w.count} mention${w.count === 1 ? '' : 's'}`, { size: 10, gap: 6 });
  });
  state.y += 6;
};

export const drawMonthOverMonth = (state, mom) => {
  if (!mom) return;
  drawSectionTitle(state, 'Month-over-month score trend');
  const sign = mom.delta > 0 ? '+' : '';
  drawParagraph(
    state,
    `${mom.previousMonth}: avg ${fmtNum(mom.previousAvg)} (${mom.previousCount} completed)  →  ${mom.currentMonth}: avg ${fmtNum(mom.currentAvg)} (${mom.currentCount} completed)  ·  Δ ${sign}${fmtNum(mom.delta)}`,
  );
};

export const drawFormulaNote = (state, formula) => {
  if (!formula) return;
  drawParagraph(state, `Placement readiness formula: ${formula}`, { size: 8, color: COLORS.muted, gap: 6 });
};

export const drawSimpleTable = (state, title, headers, rows) => {
  drawSectionTitle(state, title);
  if (!rows?.length) {
    drawParagraph(state, 'No rows to display.', { color: COLORS.muted });
    return;
  }
  const { doc } = state;
  const colW = CONTENT_W / headers.length;
  state.ensureSpace(24);
  setFill(doc, COLORS.teal);
  doc.rect(MARGIN, state.y - 10, CONTENT_W, 20, 'F');
  setText(doc, COLORS.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  headers.forEach((h, i) => doc.text(h, MARGIN + 8 + i * colW, state.y + 3));
  state.y += 16;
  rows.forEach((cells, idx) => {
    state.ensureSpace(18);
    if (idx % 2 === 0) {
      setFill(doc, COLORS.white);
      doc.rect(MARGIN, state.y - 10, CONTENT_W, 18, 'F');
    }
    setText(doc, COLORS.ink);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    cells.forEach((cell, i) => {
      doc.text(String(cell ?? '—').slice(0, 28), MARGIN + 8 + i * colW, state.y + 2);
    });
    state.y += 18;
  });
  state.y += 10;
};

/** Render one institution report onto the current/new pages of `state`. */
export const renderInstitutionReportPages = (state, report, { isContinuation = false } = {}) => {
  if (isContinuation) {
    drawFooter(state.doc);
    state.doc.addPage();
    paintPageBackground(state.doc);
    state.y = MARGIN;
  }

  drawReportHeader(state, {
    title: report.institutionName,
    subtitle: 'Institution performance report',
    generatedAt: report.generatedAt,
    dateRangeLabel: report.dateRange?.label,
  });

  const s = report.summary;
  drawStatBlock(state, [
    { label: 'Total students', value: fmtNum(s.totalStudents) },
    { label: 'Interviews', value: fmtNum(s.totalInterviews) },
    { label: 'Completion rate', value: s.completionRate == null ? '—' : `${s.completionRate}%` },
    { label: 'Interview readiness', value: fmtNum(s.fluentReadinessAvg) },
    { label: 'Placement readiness', value: s.placementReadinessPct == null ? '—' : `${s.placementReadinessPct}%` },
    { label: 'Completed', value: fmtNum(s.completedInterviews) },
  ]);

  drawFormulaNote(state, report.placementReadinessFormula);
  drawBandChart(state, report.readinessBands);
  drawSubScoreSection(state, report.subScores);
  drawPerformersTable(state, 'Top performing students', report.topPerformers);
  drawPerformersTable(state, 'Bottom performing students', report.bottomPerformers);
  drawWeaknesses(state, report.weaknesses);
  drawMonthOverMonth(state, report.monthOverMonth);
  drawFooter(state.doc);
};

export const renderStudentReportPages = (state, report) => {
  drawReportHeader(state, {
    title: report.studentName,
    subtitle: `Student performance · ${report.institutionName}`,
    generatedAt: report.generatedAt,
    dateRangeLabel: report.dateRange?.label,
  });

  const s = report.summary;
  drawStatBlock(state, [
    { label: 'Interviews', value: fmtNum(s.totalInterviews) },
    { label: 'Completed', value: fmtNum(s.completedInterviews) },
    { label: 'Completion rate', value: s.completionRate == null ? '—' : `${s.completionRate}%` },
    { label: 'Interview readiness', value: fmtNum(s.fluentReadinessAvg) },
    { label: 'Readiness band', value: s.readinessLevel || '—' },
    { label: 'Email', value: (report.studentEmail || '—').slice(0, 22) },
  ]);

  drawSubScoreSection(state, report.subScores);
  drawWeaknesses(state, report.weaknesses);
  drawMonthOverMonth(state, report.monthOverMonth);

  if (report.recentInterviews?.length) {
    drawSimpleTable(
      state,
      'Recent completed interviews',
      ['Company', 'Type', 'Score', 'Date'],
      report.recentInterviews.map((iv) => [
        iv.company,
        iv.type,
        fmtNum(iv.score),
        shortDate(iv.date),
      ]),
    );
  }

  drawFooter(state.doc);
};

export const renderCombinedComparisonPage = (state, comparison) => {
  drawReportHeader(state, {
    title: 'Institutions comparison',
    subtitle: 'Combined performance report',
    generatedAt: comparison.generatedAt,
    dateRangeLabel: 'All institutions · live platform data',
  });

  drawStatBlock(state, [
    { label: 'Institutions', value: fmtNum(comparison.institutionCount) },
    { label: 'Total students', value: fmtNum(comparison.totalStudents) },
    { label: 'Total interviews', value: fmtNum(comparison.totalInterviews) },
    { label: 'Overall readiness', value: comparison.overallReadiness == null ? '—' : `${comparison.overallReadiness}%` },
  ]);

  drawSimpleTable(
    state,
    'Institution ranking by placement readiness',
    ['Institution', 'Students', 'Interviews', 'Completion %', 'Readiness %'],
    comparison.rows.map((r) => [
      r.name,
      fmtNum(r.students),
      fmtNum(r.interviews),
      r.completionRate == null ? '—' : `${r.completionRate}%`,
      r.readiness == null ? '—' : `${r.readiness}%`,
    ]),
  );

  drawFooter(state.doc);
};

export const downloadInstitutionPdf = (report) => {
  const state = createReportDoc(report.institutionName);
  renderInstitutionReportPages(state, report);
  const safe = String(report.institutionName).replace(/[^\w\-]+/g, '_').slice(0, 48);
  state.doc.save(`VFSTR_AI_${safe}_report.pdf`);
};

export const downloadCombinedInstitutionsPdf = (reports, comparison) => {
  const state = createReportDoc('Institutions combined');
  renderCombinedComparisonPage(state, comparison);
  reports.forEach((report, index) => {
    renderInstitutionReportPages(state, report, { isContinuation: true });
    // keep index referenced for future per-page labels
    void index;
  });
  state.doc.save('VFSTR_AI_Institutions_Combined_Report.pdf');
};

export const downloadStudentPdf = (report) => {
  const state = createReportDoc(report.studentName);
  renderStudentReportPages(state, report);
  const safe = String(report.studentName).replace(/[^\w\-]+/g, '_').slice(0, 48);
  state.doc.save(`VFSTR_AI_${safe}_performance.pdf`);
};

export const downloadCandidate360Pdf = ({ user, aggregates, interviews, terminationHistory }) => {
  const state = createReportDoc(`${user.name} — 360° Report`);
  const { doc } = state;
  let y = state.y;

  doc.setFontSize(14);
  setText(doc, COLORS.ink);
  doc.text(`${user.name}`, MARGIN, y);
  y += 18;
  doc.setFontSize(10);
  setText(doc, COLORS.muted);
  doc.text([user.email, user.institution, user.batch, user.branch].filter(Boolean).join(' · '), MARGIN, y);
  y += 24;

  const lines = [
    `Readiness: ${aggregates.readinessScore}%`,
    `Average score: ${aggregates.averageScore}`,
    `Technical avg: ${aggregates.technicalAverage}`,
    `Communication avg: ${aggregates.communicationAverage}`,
    `Interviews: ${aggregates.totalInterviews} (${aggregates.completedInterviews} completed)`,
  ];
  lines.forEach((line) => {
    setText(doc, COLORS.ink);
    doc.text(line, MARGIN, y);
    y += 14;
  });
  y += 8;

  const section = (title, items) => {
    if (!items?.length) return;
    setText(doc, COLORS.tealDark);
    doc.setFontSize(11);
    doc.text(title, MARGIN, y);
    y += 14;
    doc.setFontSize(9);
    setText(doc, COLORS.ink);
    items.slice(0, 8).forEach((item) => {
      doc.text(`• ${String(item).slice(0, 90)}`, MARGIN + 8, y);
      y += 12;
    });
    y += 6;
  };

  section('Strengths', aggregates.strengths);
  section('Weaknesses', aggregates.weaknesses);
  section('Areas for improvement', aggregates.improvements);

  if (interviews?.length) {
    setText(doc, COLORS.tealDark);
    doc.setFontSize(11);
    doc.text('Recent interviews', MARGIN, y);
    y += 14;
    doc.setFontSize(9);
    interviews.slice(0, 10).forEach((iv) => {
      const line = `${iv.date ? new Date(iv.date).toLocaleDateString() : '—'} · ${iv.targetCompany || '—'} · ${iv.type} · ${iv.score || '—'}`;
      setText(doc, COLORS.ink);
      doc.text(line.slice(0, 100), MARGIN, y);
      y += 12;
    });
  }

  if (terminationHistory?.length) {
    y += 8;
    setText(doc, COLORS.tealDark);
    doc.setFontSize(11);
    doc.text('Termination history', MARGIN, y);
    y += 14;
    doc.setFontSize(9);
    terminationHistory.forEach((ev) => {
      setText(doc, COLORS.ink);
      doc.text(`${new Date(ev.terminatedAt).toLocaleString()} — ${String(ev.reason).slice(0, 80)}`, MARGIN, y);
      y += 12;
    });
  }

  drawFooter(doc);
  const safe = String(user.name).replace(/[^\w\-]+/g, '_').slice(0, 48);
  doc.save(`VFSTR_AI_${safe}_360_report.pdf`);
};

export default {
  downloadInstitutionPdf,
  downloadCombinedInstitutionsPdf,
  downloadStudentPdf,
  downloadCandidate360Pdf,
};
